on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: napari/packaging/.github/workflows/make_bundle_conda.yml@always-pyside
    with:
      event_name: ${{ github.event_name }}
